baseURL = "https://dev.barcelona-declaration.org"
languageCode = "en-us"
title = "Barcelona Declaration on Open Research Information"
contentdir = "content"
theme = "beautifulhugo"
enableRobotsTXT = true

[Params]
  selfHosted = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Preamble"
    url = "preamble/"
    weight = 1.1

[[menu.main]]
    name = "Commitments"
    url = "commitments/"
    weight = 2

[[menu.main]]
    name = "Background and Context"
    url = "background_and_context/"
    weight = 3

[[menu.main]]
    name = "Definitions"
    url = "definitions/"
    weight = 4

[[menu.main]]
    name = "Signatories"
    url = "signatories/"
    weight = 5

[[menu.main]]
    identifier = "translations"
    name = "Translations"
    url = "translations/"
    weight = 6

[[menu.main]]
    name = "Translation"
    url = "translations/"
    parent = "translations"
    weight = 1

[[menu.main]]
    name = "汉语"
    url = "translations/汉语"
    parent = "translations"
    weight = 2

[[menu.main]]
    name = "Deutsch"
    url = "translations/deutsch.pdf"
    parent = "translations"
    weight = 3

[[menu.main]]
    name = "Español"
    url = "translations/español"
    parent = "translations"
    weight = 4

[[menu.main]]
    name = "Français"
    url = "translations/français"
    parent = "translations"
    weight = 5

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 7

