baseURL = "https://barcelona-declaration.org"
languageCode = "en-us"
title = "Barcelona Declaration on Open Research Information"
contentdir = "content"
theme = "beautifulhugo"

[Params]
  selfHosted = true